### ISSUE TITLE
Adding Register Helper fields to field attribute in shortcode yields unexpected results

### ISSUE THREAD

**Issue by bluesteamhost** [strangerstudios/pmpro-membership-maps#31] opened 2021-03-09 12:46 UTC
**Describe the bug**
The Maps addon has the fields attribute for shortcode. Adding the additional fields to the shortcode yields unexpected results in the map marker info window.

**To Reproduce**
1. Install the Maps Addon and Register Helper is installed for PMPro
2. Create additional fields for Register Helper
3. Add the shortcode [pmpro_membership_maps] to any post
4. Add the fields attribute with any of the register helper fields you created in step 2
5. Load the Google Map and check the marker info window of any of the markers.

**Screenshots**
![register_helper_fields](https://user-images.githubusercontent.com/44110924/110469926-e782b800-80e2-11eb-89a9-4048b96900df.png)
![shortcode_attribute](https://user-images.githubusercontent.com/44110924/110469965-f5383d80-80e2-11eb-91da-f81ada8a8156.png)
![profile_field_values](https://user-images.githubusercontent.com/44110924/110469973-f7020100-80e2-11eb-80c5-1709be41fac7.png)
![info_window](https://user-images.githubusercontent.com/44110924/110469979-f8cbc480-80e2-11eb-9d3c-f66184e5999c.png)

**Expected behavior**
All fields specified in the field attribute must display its LABEL and VALUE underneath each other in the info window of the marker.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

> Wordpress 5.6.2
> PMPro 2.5.6
> Member Directory 1.1
> Maps Addon 0.2
> Register Helper 1.7
> PHP 7.4

</details>

**Comment by JarrydLong** [comment] 2021-03-15 18:13
Thank you for bringing this to our attention. This issue has been fixed in PR #34

**Comment by aquiferweb** [comment] 2021-03-23 14:31
Having similar issues here with Register Helper fields.
No additional fields show up at all on the map marker when added in shortcode e.g. 
[pmpro_membership_maps show_avatar="0" zoom="6" fields="churchname,denomination,church_postcode"]

![image](https://user-images.githubusercontent.com/6704738/112162564-14a39000-8be4-11eb-9144-414dde019945.png)

Using the PR34 code allows one of the additional fields to show up, but with the value of a different field (similar to @bluesteamhost above). here the value of 'denomination' is displayed as 'churchname' (also not displaying the field name properly)
![image](https://user-images.githubusercontent.com/6704738/112162749-41f03e00-8be4-11eb-9f8f-0ed193d80714.png)

**Comment by wolvyreen** [comment] 2021-03-23 14:52
> Having similar issues here with Register Helper fields.
> No additional fields show up at all on the map marker when added in shortcode e.g.
> [pmpro_membership_maps show_avatar="0" zoom="6" fields="churchname,denomination,church_postcode"]
> 
> ![image](https://user-images.githubusercontent.com/6704738/112162564-14a39000-8be4-11eb-9144-414dde019945.png)
> 
> Using the PR34 code allows one of the additional fields to show up, but with the value of a different field (similar to @bluesteamhost above). here the value of 'denomination' is displayed as 'churchname' (also not displaying the field name properly)
> ![image](https://user-images.githubusercontent.com/6704738/112162749-41f03e00-8be4-11eb-9f8f-0ed193d80714.png)

What does your shortcode look like and can we see the register helper field code?

**Comment by bluesteamhost** [comment] 2021-03-23 15:22
> Having similar issues here with Register Helper fields.
> No additional fields show up at all on the map marker when added in shortcode e.g.
> [pmpro_membership_maps show_avatar="0" zoom="6" fields="churchname,denomination,church_postcode"]
> 
> Using the PR34 code allows one of the additional fields to show up, but with the value of a different field (similar to @bluesteamhost above). here the value of 'denomination' is displayed as 'churchname' (also not displaying the field name properly)

Your shortcode looks fine although, in the shortcode, you might want to change churchname to Church Name instead.

The shortcode fields are structured as follows:

`[pmpro_membership_maps show_avatar="0" zoom="6" fields="Chuch Name,churchname;Denomination,denomination;Postal Code,church_postcode;"]`

Notice the semi-colons as the separator for the Label and field.

I have already mentioned in one of my support tickets to the team that they need to update the documentation because it does not mention the proper structure to use.

**Comment by aquiferweb** [comment] 2021-03-23 17:50
Ah -  I didn't realise that structure was needed... That would explain some
of the other weird behaviour I was seeing!

Thanks,
Tim

**Comment by aquiferweb** [comment] 2021-03-23 17:56
I can confirm that changing the structure of the fields part of the shortcode like:

fields = "[display name],[variablename];[display_name2],[variablename2]"

And using the pull request #34 code, it seems to be working as expected now - thanks for the assistance @bluesteamhost and @JarrydLong

**Comment by andrewlimaza** [comment] 2022-05-26 09:29
Resolved with https://github.com/strangerstudios/pmpro-membership-maps/pull/34

**Closed as completed by andrewlimaza** 2022-05-26 09:29 UTC
